import { EndInterviewQuestion, type InterviewRound } from "./contracts";

/**
 * Production-ready End-of-Interview Question Bank.
 *
 * Grouped across the 4 interviewer rounds:
 * - recruiter
 * - hiring-manager
 * - technical
 * - executive
 *
 * Designed to provide candidates with natural, non-generic, spoken-ready questions
 * that reveal:
 * - role success criteria
 * - team structure
 * - current pain points
 * - technical scope & tradeoffs
 * - company priorities
 * - growth expectations
 * - process & next steps
 */
export const END_OF_INTERVIEW_QUESTION_BANK: Record<InterviewRound, EndInterviewQuestion[]> = {
  recruiter: [
    EndInterviewQuestion.parse({
      question: "What does the timeline and evaluation sequence look like between now and a final hiring decision?",
      context: "Clarifies interview pipeline stages, decision makers, and anticipated start timeline.",
      round: "recruiter",
      priority: 1,
      category: "Compensation",
      followUpNote: "Listen for concrete dates and decision owner names.",
      expectedAnswer: "A clear multi-round schedule with specific timeframes for feedback and an offer timeline.",
      redFlag: "Vagueness about remaining steps, indeterminate review committees, or unclear role budget.",
      professionalExample: "I have ongoing conversations, so aligning our calendars helps me manage offer timings cleanly.",
    }),
    EndInterviewQuestion.parse({
      question: "What prompted opening this role now, and what distinguishes a good hire from an exceptional hire?",
      context: "Identifies whether this is backfill or growth and surfaces the true bar for success.",
      round: "recruiter",
      priority: 2,
      category: "Growth",
      followUpNote: "Check if backfill due to attrition or new headcount for a major initiative.",
      expectedAnswer: "Speaks to high-priority business expansion or specific skill gaps the team urgently needs filled.",
      redFlag: "Uncertainty about why the position opened or high historical churn in this specific seat.",
      professionalExample: "Understanding what differentiates top performers early helps me calibrate my impact from day one.",
    }),
    EndInterviewQuestion.parse({
      question: "How is this organization structured across product and engineering, and where does this team plug in?",
      context: "Validates team topography, reporting lines, and stakeholder relationships.",
      round: "recruiter",
      priority: 2,
      category: "Team",
      followUpNote: "Listen for cross-functional squad ratios and executive alignment.",
      expectedAnswer: "Articulates clear squad models, designated PM/design counterparts, and healthy engineering ratios.",
      redFlag: "Siloed departments, disconnected management layers, or absence of dedicated product partners.",
      professionalExample: "I thrive in tight cross-functional loops where engineering collaborates directly with product.",
    }),
    EndInterviewQuestion.parse({
      question: "Where have candidates typically struggled during the interview process or within their first ninety days?",
      context: "Uncovers hidden friction points and realistic hurdles candidates face.",
      round: "recruiter",
      priority: 2,
      category: "Culture",
      followUpNote: "Note whether friction is technical complexity, autonomy, or cross-team collaboration.",
      expectedAnswer: "Highlights specific demands like ramping on domain complexity, navigating legacy systems, or high ownership.",
      redFlag: "Defensiveness, blaming past candidates, or evasive non-answers like 'they just weren't a fit'.",
      professionalExample: "Knowing the steepest parts of the learning curve helps me prepare targeted ramp-up strategies.",
    }),
    EndInterviewQuestion.parse({
      question: "Could you share the budgeted compensation band and how equity or bonus components are structured?",
      context: "Aligns financial expectations early to prevent late-stage compensation mismatches.",
      round: "recruiter",
      priority: 2,
      category: "Compensation",
      followUpNote: "Listen for base salary range, vesting cadence, and bonus achievement track records.",
      expectedAnswer: "Transparent disclosure of base salary brackets, target bonus percentages, and equity refresh cycles.",
      redFlag: "Refusal to provide any range, withholding equity details, or deflection until post-offer stage.",
      professionalExample: "Ensuring we are aligned on compensation early ensures everyone's time is respected throughout the process.",
    }),
    EndInterviewQuestion.parse({
      question: "How does the organization evaluate performance and leveling progression once someone establishes their core delivery?",
      context: "Understands career trajectory, promotion cadence, and performance review transparency.",
      round: "recruiter",
      priority: 3,
      category: "Growth",
      followUpNote: "Look for bi-annual or annual cycles with published competency rubrics.",
      expectedAnswer: "Structured performance frameworks, regular calibration cycles, and clear promotion criteria.",
      redFlag: "Ad-hoc promotions based solely on manager discretion without documented leveling expectations.",
      professionalExample: "I value environments where sustained high performance and broader technical impact have clear recognition pathways.",
    }),
  ],

  "hiring-manager": [
    EndInterviewQuestion.parse({
      question: "What does an exceptional first six months look like for whoever takes this role?",
      context: "Establishes concrete deliverables, early milestones, and manager expectations.",
      round: "hiring-manager",
      priority: 1,
      category: "Delivery",
      followUpNote: "Listen for 30/60/90 milestones and specific production impact metrics.",
      expectedAnswer: "Clear milestones: independent PRs in 30 days, owning a feature release by 90 days, leading architectural decisions by 180 days.",
      redFlag: "Vague goals like 'just get up to speed' or unreasonable expectations without onboarding support.",
      professionalExample: "I like to align early on verifiable milestones so we can review trajectory against mutual targets.",
    }),
    EndInterviewQuestion.parse({
      question: "What is currently the single biggest bottleneck preventing the team from shipping at their desired velocity?",
      context: "Exposes real technical and process pain points inside the engineering unit.",
      round: "hiring-manager",
      priority: 2,
      category: "Operations",
      followUpNote: "Notice whether blockers are CI/CD slowness, QA handoffs, dependencies, or changing specs.",
      expectedAnswer: "Frank diagnosis: slow test suites, cross-team API dependencies, or ongoing technical debt payoff.",
      redFlag: "Insistence that everything is flawless, or blaming the engineers for lack of speed.",
      professionalExample: "Identifying systemic delivery friction is usually where I find high-leverage opportunities to unblock engineers.",
    }),
    EndInterviewQuestion.parse({
      question: "How are architectural and product decisions made between your team, staff engineers, and product management?",
      context: "Assesses team autonomy, technical leadership influence, and product collaboration.",
      round: "hiring-manager",
      priority: 2,
      category: "Architecture",
      followUpNote: "Look for RFC processes, lightweight consensus, and engineer-driven design authority.",
      expectedAnswer: "Engineers write design docs with peer reviews; PMs define problem spaces while engineers own the architecture.",
      redFlag: "Top-down feature dictation with zero technical consultation, or analysis paralysis without decision owners.",
      professionalExample: "In my experience, the strongest systems arise when engineers and product co-design solutions from the inception phase.",
    }),
    EndInterviewQuestion.parse({
      question: "Where is the team currently making conscious compromises between short-term delivery commitments and longer-term platform stability?",
      context: "Surfaces tech debt management, architectural tradeoffs, and delivery pressure reality.",
      round: "hiring-manager",
      priority: 2,
      category: "Infrastructure",
      followUpNote: "Listen for dedicated debt budgets, maintenance sprints, or intentional tradeoff discipline.",
      expectedAnswer: "Identifies specific deferred refactors with explicit roadmap commitments to remediate them.",
      redFlag: "Denial of tech debt existence, or chronic accumulation with zero refactoring bandwidth permitted.",
      professionalExample: "Managing technical debt as a conscious loan with an intentional repayment schedule keeps platforms sustainable.",
    }),
    EndInterviewQuestion.parse({
      question: "How does this team's roadmap directly connect to the company's top executive priorities for this fiscal year?",
      context: "Verifies strategic importance, team visibility, and organizational investment.",
      round: "hiring-manager",
      priority: 2,
      category: "Strategy",
      followUpNote: "Check if the team is on a revenue path, core platform foundation, or peripheral support duty.",
      expectedAnswer: "Direct line of sight from team sprint goals to company OKRs and executive revenue drivers.",
      redFlag: "Isolation from business outcomes, feeling forgotten, or building features nobody measures.",
      professionalExample: "Knowing how our daily commits influence company objectives helps engineers make smarter trade-offs in design.",
    }),
    EndInterviewQuestion.parse({
      question: "What does your team's onboarding look like, and how quickly is a new engineer expected to deploy to production?",
      context: "Measures developer experience tooling, documentation quality, and team psychological safety.",
      round: "hiring-manager",
      priority: 3,
      category: "Team",
      followUpNote: "Look for automated dev environment setup, onboarding buddies, and day-one deploy capability.",
      expectedAnswer: "Documented setup scripts, pairing buddies, and a first minor bugfix deployed within week one.",
      redFlag: "Weeks of waiting for access permissions, broken documentation, or sink-or-swim attitude.",
      professionalExample: "A streamlined onboarding path reflects strong engineering hygiene and developer tooling discipline.",
    }),
  ],

  technical: [
    EndInterviewQuestion.parse({
      question: "What architectural decision made in the last year is the team most proud of, and what was the tradeoff?",
      context: "Reveals technical judgment, engineering values, and real-world system design depth.",
      round: "technical",
      priority: 1,
      category: "Architecture",
      followUpNote: "Listen for genuine tradeoffs (latency vs consistency, operational complexity vs feature velocity).",
      expectedAnswer: "Detailed discussion of a concrete migration, decoupling, or storage choice with candid reflection on costs.",
      redFlag: "Claims of zero downsides, chasing buzzwords without business rationale, or inability to name any major design.",
      professionalExample: "Architecture is fundamentally about picking the right set of problems; hearing your tradeoffs gives great insight into team values.",
    }),
    EndInterviewQuestion.parse({
      question: "What does on-call and incident frequency actually feel like week to week for an engineer on this team?",
      context: "Exposes system reliability, operational health, sleep quality, and alert noise levels.",
      round: "technical",
      priority: 2,
      category: "Operations",
      followUpNote: "Note rotation frequency, secondary escalations, blameless postmortem culture, and pager fatigue.",
      expectedAnswer: "Clear rotation schedules, manageable page volumes (<2 per shift), actionable runbooks, and blameless postmortems.",
      redFlag: "Chronic 3 AM pages, engineers acting as human glue for fragile pipelines, or finger-pointing postmortems.",
      professionalExample: "System health is reflected in operational quiet; blameless retros and alert hygiene protect engineer focus.",
    }),
    EndInterviewQuestion.parse({
      question: "What is the biggest infrastructure or CI/CD pain point that engineers complain about during retros?",
      context: "Assesses daily developer friction, build pipelines, test flakiness, and release frequency.",
      round: "technical",
      priority: 2,
      category: "Infrastructure",
      followUpNote: "Look for pipeline duration, flaky tests, staging fidelity, and trunk-based deployment practices.",
      expectedAnswer: "Specific, self-aware complaints: 25-minute test suites, staging environment drift, or slow container cold starts.",
      redFlag: "Manual deployment checklists on Fridays, fear of releasing, or lack of automated rollbacks.",
      professionalExample: "Developer velocity depends on rapid feedback loops; fixing pipeline bottlenecks provides outsized leverage.",
    }),
    EndInterviewQuestion.parse({
      question: "How do technical RFCs and design proposals move from initial idea to production implementation?",
      context: "Understands engineering governance, peer review culture, and technical consensus building.",
      round: "technical",
      priority: 2,
      category: "Delivery",
      followUpNote: "Notice whether proposals encourage constructive debate or get bogged down in politics.",
      expectedAnswer: "Written RFC templates, scheduled review forums, time-boxed feedback, and clear technical lead sign-offs.",
      redFlag: "Cowboy commits without design reviews, or paralyzing committee bureaucracy where decisions languish.",
      professionalExample: "Well-structured RFCs ensure architecture survives personnel changes while giving every engineer a voice in design.",
    }),
    EndInterviewQuestion.parse({
      question: "How does the team balance rigorous code review standards with maintaining high daily momentum?",
      context: "Evaluates pull request turnaround times, review quality, and team collaboration hygiene.",
      round: "technical",
      priority: 2,
      category: "Delivery",
      followUpNote: "Listen for SLA on PR reviews (<24h), lint automation, and constructive tone in comments.",
      expectedAnswer: "Automated linters handle style; reviewers focus on correctness, security, and edge cases; fast review turnarounds.",
      redFlag: "PRs stagnating for weeks, bike-shedding over formatting, or rubber-stamp approvals without testing.",
      professionalExample: "Keeping PRs small and decoupling nitpicks from blocking concerns keeps shipping momentum fast and healthy.",
    }),
    EndInterviewQuestion.parse({
      question: "How are cross-cutting concerns like authentication, audit compliance, and data privacy enforced across services?",
      context: "Tests security maturity, distributed governance, and platform abstraction layers.",
      round: "technical",
      priority: 3,
      category: "Security",
      followUpNote: "Check for shared libraries, API gateway middleware, service meshes, or centralized auth tokens.",
      expectedAnswer: "Standardized platform middleware, zero-trust tokens, automated secrets management, and automated security scans.",
      redFlag: "Ad-hoc per-service auth logic, hardcoded secrets, or leaving security reviews until production week.",
      professionalExample: "Treating security and observability as platform primitives frees product engineers to focus on business features safely.",
    }),
  ],

  executive: [
    EndInterviewQuestion.parse({
      question: "What is the company's most critical strategic bet over the next two years, and what must go right to win?",
      context: "Uncovers long-term vision, market positioning, competitive threats, and resource allocation.",
      round: "executive",
      priority: 1,
      category: "Strategy",
      followUpNote: "Listen for customer-focused differentiation vs defensive copycatting.",
      expectedAnswer: "Articulates an inspiring, concrete market expansion, platform shift, or enterprise customer category bet.",
      redFlag: "Fluffy corporate slogans with no substance, or inability to name key competitive threats.",
      professionalExample: "Understanding the primary company bet allows senior engineers to architect systems that scale with business expansion.",
    }),
    EndInterviewQuestion.parse({
      question: "When you look at this engineering organization a year from now, what capability or metric must be radically improved?",
      context: "Reveals leadership expectations, organizational maturity targets, and executive pain points.",
      round: "executive",
      priority: 2,
      category: "Growth",
      followUpNote: "Look for operational resilience, customer delivery speed, platform stability, or innovation cadence.",
      expectedAnswer: "Highlights concrete capability shifts: moving from monolithic releases to continuous deployment, or sub-second enterprise latency.",
      redFlag: "Focus purely on vanity metrics, or lack of awareness of engineering's core operational capabilities.",
      professionalExample: "Senior contributors should align architectural investments directly to the organizational capabilities executives need unlocked.",
    }),
    EndInterviewQuestion.parse({
      question: "How do you ensure engineering investments stay tightly aligned with revenue outcomes rather than accumulating speculative technology?",
      context: "Exposes business-technology alignment, capital discipline, and engineering ROI evaluation.",
      round: "executive",
      priority: 2,
      category: "Strategy",
      followUpNote: "Check how tech initiatives are funded and whether engineering leadership has a seat at the commercial table.",
      expectedAnswer: "Co-ownership of business KPIs between engineering VPs and product/business leaders; transparent roadmap trade-offs.",
      redFlag: "Engineering viewed strictly as an IT cost center to be minimized, or runaway tech projects detached from customer value.",
      professionalExample: "The most durable technology decisions justify themselves in customer retention, operating margins, or product velocity.",
    }),
    EndInterviewQuestion.parse({
      question: "What internal friction or operational challenge concerns you most as the organization scales its headcount and customer base?",
      context: "Surfaces executive-level realism about organizational growing pains and scaling limits.",
      round: "executive",
      priority: 2,
      category: "Operations",
      followUpNote: "Note whether concerns relate to communication overhead, product fragmentation, or loss of cultural speed.",
      expectedAnswer: "Candid insights on cross-team dependency management, preserving engineering ownership, and preventing bureaucratic drag.",
      redFlag: "Denial of any scaling challenges, or disconnect from the day-to-day realities of the working staff.",
      professionalExample: "Recognizing scaling friction early allows senior leaders to build architectural boundaries that mirror independent team ownership.",
    }),
    EndInterviewQuestion.parse({
      question: "What cultural attribute has been essential to getting the company here that you are actively fighting to preserve as you grow?",
      context: "Explores core values, founder mindset, leadership integrity, and cultural retention.",
      round: "executive",
      priority: 3,
      category: "Culture",
      followUpNote: "Listen for authentic operating principles (speed, ownership, candidate transparency, blamelessness).",
      expectedAnswer: "Names a specific behavior—such as high autonomy, bias for action, or customer obsession—and shares how leadership reinforces it.",
      redFlag: "Cynicism, generic HR platitudes, or values that contradict how leadership actually treats staff.",
      professionalExample: "Culture is defined by what leaders reward and tolerate; knowing the foundational principles guides how we lead our teams.",
    }),
  ],
};
